package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/shav/telegram-bot/internal/modules/finances/commands/spendings_report_command.useCase -o ./mocks\use_case.go -n UseCaseMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/shav/telegram-bot/internal/common/date"
)

// UseCaseMock implements finance_commands_spendings_report.useCase
type UseCaseMock struct {
	t minimock.Tester

	funcRequestSpendingReport          func(ctx context.Context, userId int64, period date.Period) (err error)
	inspectFuncRequestSpendingReport   func(ctx context.Context, userId int64, period date.Period)
	afterRequestSpendingReportCounter  uint64
	beforeRequestSpendingReportCounter uint64
	RequestSpendingReportMock          mUseCaseMockRequestSpendingReport
}

// NewUseCaseMock returns a mock for finance_commands_spendings_report.useCase
func NewUseCaseMock(t minimock.Tester) *UseCaseMock {
	m := &UseCaseMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RequestSpendingReportMock = mUseCaseMockRequestSpendingReport{mock: m}
	m.RequestSpendingReportMock.callArgs = []*UseCaseMockRequestSpendingReportParams{}

	return m
}

type mUseCaseMockRequestSpendingReport struct {
	mock               *UseCaseMock
	defaultExpectation *UseCaseMockRequestSpendingReportExpectation
	expectations       []*UseCaseMockRequestSpendingReportExpectation

	callArgs []*UseCaseMockRequestSpendingReportParams
	mutex    sync.RWMutex
}

// UseCaseMockRequestSpendingReportExpectation specifies expectation struct of the useCase.RequestSpendingReport
type UseCaseMockRequestSpendingReportExpectation struct {
	mock    *UseCaseMock
	params  *UseCaseMockRequestSpendingReportParams
	results *UseCaseMockRequestSpendingReportResults
	Counter uint64
}

// UseCaseMockRequestSpendingReportParams contains parameters of the useCase.RequestSpendingReport
type UseCaseMockRequestSpendingReportParams struct {
	ctx    context.Context
	userId int64
	period date.Period
}

// UseCaseMockRequestSpendingReportResults contains results of the useCase.RequestSpendingReport
type UseCaseMockRequestSpendingReportResults struct {
	err error
}

// Expect sets up expected params for useCase.RequestSpendingReport
func (mmRequestSpendingReport *mUseCaseMockRequestSpendingReport) Expect(ctx context.Context, userId int64, period date.Period) *mUseCaseMockRequestSpendingReport {
	if mmRequestSpendingReport.mock.funcRequestSpendingReport != nil {
		mmRequestSpendingReport.mock.t.Fatalf("UseCaseMock.RequestSpendingReport mock is already set by Set")
	}

	if mmRequestSpendingReport.defaultExpectation == nil {
		mmRequestSpendingReport.defaultExpectation = &UseCaseMockRequestSpendingReportExpectation{}
	}

	mmRequestSpendingReport.defaultExpectation.params = &UseCaseMockRequestSpendingReportParams{ctx, userId, period}
	for _, e := range mmRequestSpendingReport.expectations {
		if minimock.Equal(e.params, mmRequestSpendingReport.defaultExpectation.params) {
			mmRequestSpendingReport.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRequestSpendingReport.defaultExpectation.params)
		}
	}

	return mmRequestSpendingReport
}

// Inspect accepts an inspector function that has same arguments as the useCase.RequestSpendingReport
func (mmRequestSpendingReport *mUseCaseMockRequestSpendingReport) Inspect(f func(ctx context.Context, userId int64, period date.Period)) *mUseCaseMockRequestSpendingReport {
	if mmRequestSpendingReport.mock.inspectFuncRequestSpendingReport != nil {
		mmRequestSpendingReport.mock.t.Fatalf("Inspect function is already set for UseCaseMock.RequestSpendingReport")
	}

	mmRequestSpendingReport.mock.inspectFuncRequestSpendingReport = f

	return mmRequestSpendingReport
}

// Return sets up results that will be returned by useCase.RequestSpendingReport
func (mmRequestSpendingReport *mUseCaseMockRequestSpendingReport) Return(err error) *UseCaseMock {
	if mmRequestSpendingReport.mock.funcRequestSpendingReport != nil {
		mmRequestSpendingReport.mock.t.Fatalf("UseCaseMock.RequestSpendingReport mock is already set by Set")
	}

	if mmRequestSpendingReport.defaultExpectation == nil {
		mmRequestSpendingReport.defaultExpectation = &UseCaseMockRequestSpendingReportExpectation{mock: mmRequestSpendingReport.mock}
	}
	mmRequestSpendingReport.defaultExpectation.results = &UseCaseMockRequestSpendingReportResults{err}
	return mmRequestSpendingReport.mock
}

//Set uses given function f to mock the useCase.RequestSpendingReport method
func (mmRequestSpendingReport *mUseCaseMockRequestSpendingReport) Set(f func(ctx context.Context, userId int64, period date.Period) (err error)) *UseCaseMock {
	if mmRequestSpendingReport.defaultExpectation != nil {
		mmRequestSpendingReport.mock.t.Fatalf("Default expectation is already set for the useCase.RequestSpendingReport method")
	}

	if len(mmRequestSpendingReport.expectations) > 0 {
		mmRequestSpendingReport.mock.t.Fatalf("Some expectations are already set for the useCase.RequestSpendingReport method")
	}

	mmRequestSpendingReport.mock.funcRequestSpendingReport = f
	return mmRequestSpendingReport.mock
}

// When sets expectation for the useCase.RequestSpendingReport which will trigger the result defined by the following
// Then helper
func (mmRequestSpendingReport *mUseCaseMockRequestSpendingReport) When(ctx context.Context, userId int64, period date.Period) *UseCaseMockRequestSpendingReportExpectation {
	if mmRequestSpendingReport.mock.funcRequestSpendingReport != nil {
		mmRequestSpendingReport.mock.t.Fatalf("UseCaseMock.RequestSpendingReport mock is already set by Set")
	}

	expectation := &UseCaseMockRequestSpendingReportExpectation{
		mock:   mmRequestSpendingReport.mock,
		params: &UseCaseMockRequestSpendingReportParams{ctx, userId, period},
	}
	mmRequestSpendingReport.expectations = append(mmRequestSpendingReport.expectations, expectation)
	return expectation
}

// Then sets up useCase.RequestSpendingReport return parameters for the expectation previously defined by the When method
func (e *UseCaseMockRequestSpendingReportExpectation) Then(err error) *UseCaseMock {
	e.results = &UseCaseMockRequestSpendingReportResults{err}
	return e.mock
}

// RequestSpendingReport implements finance_commands_spendings_report.useCase
func (mmRequestSpendingReport *UseCaseMock) RequestSpendingReport(ctx context.Context, userId int64, period date.Period) (err error) {
	mm_atomic.AddUint64(&mmRequestSpendingReport.beforeRequestSpendingReportCounter, 1)
	defer mm_atomic.AddUint64(&mmRequestSpendingReport.afterRequestSpendingReportCounter, 1)

	if mmRequestSpendingReport.inspectFuncRequestSpendingReport != nil {
		mmRequestSpendingReport.inspectFuncRequestSpendingReport(ctx, userId, period)
	}

	mm_params := &UseCaseMockRequestSpendingReportParams{ctx, userId, period}

	// Record call args
	mmRequestSpendingReport.RequestSpendingReportMock.mutex.Lock()
	mmRequestSpendingReport.RequestSpendingReportMock.callArgs = append(mmRequestSpendingReport.RequestSpendingReportMock.callArgs, mm_params)
	mmRequestSpendingReport.RequestSpendingReportMock.mutex.Unlock()

	for _, e := range mmRequestSpendingReport.RequestSpendingReportMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRequestSpendingReport.RequestSpendingReportMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRequestSpendingReport.RequestSpendingReportMock.defaultExpectation.Counter, 1)
		mm_want := mmRequestSpendingReport.RequestSpendingReportMock.defaultExpectation.params
		mm_got := UseCaseMockRequestSpendingReportParams{ctx, userId, period}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRequestSpendingReport.t.Errorf("UseCaseMock.RequestSpendingReport got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRequestSpendingReport.RequestSpendingReportMock.defaultExpectation.results
		if mm_results == nil {
			mmRequestSpendingReport.t.Fatal("No results are set for the UseCaseMock.RequestSpendingReport")
		}
		return (*mm_results).err
	}
	if mmRequestSpendingReport.funcRequestSpendingReport != nil {
		return mmRequestSpendingReport.funcRequestSpendingReport(ctx, userId, period)
	}
	mmRequestSpendingReport.t.Fatalf("Unexpected call to UseCaseMock.RequestSpendingReport. %v %v %v", ctx, userId, period)
	return
}

// RequestSpendingReportAfterCounter returns a count of finished UseCaseMock.RequestSpendingReport invocations
func (mmRequestSpendingReport *UseCaseMock) RequestSpendingReportAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRequestSpendingReport.afterRequestSpendingReportCounter)
}

// RequestSpendingReportBeforeCounter returns a count of UseCaseMock.RequestSpendingReport invocations
func (mmRequestSpendingReport *UseCaseMock) RequestSpendingReportBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRequestSpendingReport.beforeRequestSpendingReportCounter)
}

// Calls returns a list of arguments used in each call to UseCaseMock.RequestSpendingReport.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRequestSpendingReport *mUseCaseMockRequestSpendingReport) Calls() []*UseCaseMockRequestSpendingReportParams {
	mmRequestSpendingReport.mutex.RLock()

	argCopy := make([]*UseCaseMockRequestSpendingReportParams, len(mmRequestSpendingReport.callArgs))
	copy(argCopy, mmRequestSpendingReport.callArgs)

	mmRequestSpendingReport.mutex.RUnlock()

	return argCopy
}

// MinimockRequestSpendingReportDone returns true if the count of the RequestSpendingReport invocations corresponds
// the number of defined expectations
func (m *UseCaseMock) MinimockRequestSpendingReportDone() bool {
	for _, e := range m.RequestSpendingReportMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RequestSpendingReportMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRequestSpendingReportCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRequestSpendingReport != nil && mm_atomic.LoadUint64(&m.afterRequestSpendingReportCounter) < 1 {
		return false
	}
	return true
}

// MinimockRequestSpendingReportInspect logs each unmet expectation
func (m *UseCaseMock) MinimockRequestSpendingReportInspect() {
	for _, e := range m.RequestSpendingReportMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UseCaseMock.RequestSpendingReport with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.RequestSpendingReportMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterRequestSpendingReportCounter) < 1 {
		if m.RequestSpendingReportMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UseCaseMock.RequestSpendingReport")
		} else {
			m.t.Errorf("Expected call to UseCaseMock.RequestSpendingReport with params: %#v", *m.RequestSpendingReportMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRequestSpendingReport != nil && mm_atomic.LoadUint64(&m.afterRequestSpendingReportCounter) < 1 {
		m.t.Error("Expected call to UseCaseMock.RequestSpendingReport")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UseCaseMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockRequestSpendingReportInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UseCaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UseCaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRequestSpendingReportDone()
}
