version: '2'
services:
  postgres-dev:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=telegram_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
networks:
  default:
    name: tgbot-network
    external: true